### PR TITLE
Update manual to 0.97

### PR DESCRIPTION
**Pull request by akrabat**
Update to version 0.97 of the manual after the release of 0.97. 

Pretty sure that only the instructions on how to run the tests changed.

### CODE REVIEW

**Comment by lornajane** [comment]
Do we need to explain how the MD5s work and how to contribute new ones? I'm a little hazy where we are at with the tests as I think we're still working on them.

**Comment by akrabat** [comment]
> Do we need to explain how the MD5s work and how to contribute new ones? I'm a little hazy where we are at with the tests as I think we're still working on them.

The manual picks it up from [DEVELOPERS.rst](https://github.com/rst2pdf/rst2pdf/blob/master/doc/DEVELOPERS.rst) which almost certainly needs a lot of love!

**Comment by lornajane** [comment]
I think this is an issue but not a blocker, so I've logged it https://github.com/rst2pdf/rst2pdf/issues/865

**Review by lornajane — APPROVED** [review]
Thanks!

**Pull request merged**
